backend:
  name: github
  repo: nk7788/CMS_test # Path to Github repository
  branch: master # Branch to update

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "assets/img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "jobs" # Used in routes, e.g., /admin/collections/blog
    label: "Jobs" # Used in the UI
    folder: "_careers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Job ID", name: "job_id", widget: "number"}
      - {label: "Position Name", name: "position_name", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Position Description", name: "position_description", widget: "markdown"}
      - {label: "Link", name: "link", widget: "string"}